# -*- coding: utf-8 -*-
"""Cat_vs_Dog_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_05xrwFXcDB-LYx_N36Xfd76GaRKEs5A

Extract & Inspect
"""

# Part 1: extract & inspect (Colab)
import os, zipfile, glob, random
from PIL import Image
import matplotlib.pyplot as plt
from collections import Counter

# 1) try to find a .zip file in common locations
zip_candidates = glob.glob('/content/*.zip') + glob.glob('/mnt/data/*.zip') + glob.glob('/*.zip') + glob.glob('*.zip')
zip_path = zip_candidates[0] if zip_candidates else None

if not zip_path:
    raise FileNotFoundError("No .zip found in working dir. Upload the zip to Colab (e.g. /content) and re-run this cell.")

print("Using zip:", zip_path)

# 2) extract (if not already extracted)
extract_dir = '/content/cats_dogs_dataset'
if not os.path.exists(extract_dir):
    os.makedirs(extract_dir, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(extract_dir)
    print("Extracted to:", extract_dir)
else:
    print("Extraction folder already exists:", extract_dir)

# 3) find cat & dog folders (case-insensitive)
cat_dirs = []
dog_dirs = []
for root, dirs, files in os.walk(extract_dir):
    for d in dirs:
        dn = d.lower()
        if dn.startswith('cat') or 'cat' == dn:
            cat_dirs.append(os.path.join(root, d))
        if dn.startswith('dog') or 'dog' == dn:
            dog_dirs.append(os.path.join(root, d))

# if not found by name, try common structure: look for folders containing many filenames with 'cat' or 'dog' in filename
if not cat_dirs or not dog_dirs:
    all_files = glob.glob(os.path.join(extract_dir, '**', '*.*'), recursive=True)
    for f in all_files:
        name = os.path.basename(f).lower()
        if 'cat' in name and os.path.splitext(f)[1].lower() in ('.jpg','.jpeg','.png','.bmp'):
            cat_dirs.append(os.path.dirname(f))
        if 'dog' in name and os.path.splitext(f)[1].lower() in ('.jpg','.jpeg','.png','.bmp'):
            dog_dirs.append(os.path.dirname(f))
    cat_dirs = list(set(cat_dirs))
    dog_dirs = list(set(dog_dirs))

print("Cat dirs found:", cat_dirs)
print("Dog dirs found:", dog_dirs)

# 4) collect image file paths
def collect_imgs(dirs_list):
    img_paths = []
    for p in dirs_list:
        for ext in ('*.jpg','*.jpeg','*.png','*.bmp'):
            img_paths += glob.glob(os.path.join(p,ext))
    return sorted(list(set(img_paths)))

cat_paths = collect_imgs(cat_dirs)
dog_paths = collect_imgs(dog_dirs)

print("Num cat images:", len(cat_paths))
print("Num dog images:", len(dog_paths))
print("Total images:", len(cat_paths)+len(dog_paths))

# 5) check for corrupted images and gather sizes
def check_and_sizes(paths, max_report=10):
    corrupt = []
    sizes = []
    for p in paths:
        try:
            with Image.open(p) as im:
                im.verify()   # verify integrity
            with Image.open(p) as im:
                sizes.append(im.size)  # (width, height)
        except Exception as e:
            corrupt.append(p)
    if len(corrupt) > 0:
        print(f"Found {len(corrupt)} corrupted images (showing up to {max_report}):")
        for c in corrupt[:max_report]:
            print(" -", c)
    return corrupt, sizes

corrupt_cats, sizes_cats = check_and_sizes(cat_paths)
corrupt_dogs, sizes_dogs = check_and_sizes(dog_paths)

print("Corrupted cats:", len(corrupt_cats))
print("Corrupted dogs:", len(corrupt_dogs))
print("Top cat sizes:", Counter(sizes_cats).most_common(5))
print("Top dog sizes:", Counter(sizes_dogs).most_common(5))

# 6) display sample images (3 cats, 3 dogs)
def show_samples(paths, n=6, title='Samples'):
    if not paths:
        print("No images to show for", title)
        return
    samples = random.sample(paths, min(n, len(paths)))
    cols = 3
    rows = (len(samples) + cols - 1) // cols
    plt.figure(figsize=(cols*3, rows*3))
    for i, p in enumerate(samples):
        img = Image.open(p).convert('RGB')
        plt.subplot(rows, cols, i+1)
        plt.imshow(img)
        plt.axis('off')
        plt.title(os.path.basename(p), fontsize=8)
    plt.suptitle(title)
    plt.show()

print("\nShowing up to 3 cat samples and 3 dog samples...")
show_samples(cat_paths, n=3, title='Cat samples')
show_samples(dog_paths, n=3, title='Dog samples')

# 7) quick peek of first few file paths
print("\nFirst 5 cat paths:", cat_paths[:5])
print("First 5 dog paths:", dog_paths[:5])

Split dataset into train/val/test

# Part 2: Split dataset into train/val/test
import os, shutil, random

# Input folders (already found in Part-1)
cat_paths = cat_paths  # from previous step
dog_paths = dog_paths

# Output base directory
split_base = "/content/cats_dogs_split"
if os.path.exists(split_base):
    shutil.rmtree(split_base)
os.makedirs(split_base, exist_ok=True)

# Ratios
train_ratio, val_ratio, test_ratio = 0.7, 0.15, 0.15

def split_and_copy(img_paths, class_name):
    n = len(img_paths)
    random.shuffle(img_paths)
    train_end = int(train_ratio*n)
    val_end   = int((train_ratio+val_ratio)*n)

    subsets = {
        'train': img_paths[:train_end],
        'val':   img_paths[train_end:val_end],
        'test':  img_paths[val_end:]
    }

    for subset, paths in subsets.items():
        outdir = os.path.join(split_base, subset, class_name)
        os.makedirs(outdir, exist_ok=True)
        for p in paths:
            shutil.copy(p, outdir)

split_and_copy(cat_paths, "cat")
split_and_copy(dog_paths, "dog")

# Verify counts
for subset in ['train','val','test']:
    c = len(os.listdir(os.path.join(split_base, subset, "cat")))
    d = len(os.listdir(os.path.join(split_base, subset, "dog")))
    print(f"{subset}: cats={c}, dogs={d}, total={c+d}")

"""Data Generators (Preprocessing)"""

# Part 3: Data Generators (Preprocessing)
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Path where Part-2 stored split data
split_base = "/content/cats_dogs_split"

# Image size (for CNN input)
img_size = (128, 128)
batch_size = 32

# Train generator with augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True
)

# Validation / test generator (no augmentation, only rescale)
test_val_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    os.path.join(split_base, "train"),
    target_size=img_size,
    batch_size=batch_size,
    class_mode="binary"
)

val_gen = test_val_datagen.flow_from_directory(
    os.path.join(split_base, "val"),
    target_size=img_size,
    batch_size=batch_size,
    class_mode="binary"
)

test_gen = test_val_datagen.flow_from_directory(
    os.path.join(split_base, "test"),
    target_size=img_size,
    batch_size=batch_size,
    class_mode="binary",
    shuffle=False
)

print("Class indices:", train_gen.class_indices)

"""Visualizations"""

# Part 3.1: Visualizations
import matplotlib.pyplot as plt
import numpy as np

# Count class distribution from generators
train_counts = train_gen.classes
val_counts = val_gen.classes
test_counts = test_gen.classes

# Plot class distribution
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.hist(train_counts, bins=np.arange(3)-0.5, rwidth=0.6)
plt.xticks([0,1], ['Cat','Dog'])
plt.title("Train set distribution")

plt.subplot(1,3,2)
plt.hist(val_counts, bins=np.arange(3)-0.5, rwidth=0.6)
plt.xticks([0,1], ['Cat','Dog'])
plt.title("Validation set distribution")

plt.subplot(1,3,3)
plt.hist(test_counts, bins=np.arange(3)-0.5, rwidth=0.6)
plt.xticks([0,1], ['Cat','Dog'])
plt.title("Test set distribution")

plt.tight_layout()
plt.show()

# Show some sample training images
sample_imgs, sample_labels = next(train_gen)  # one batch
plt.figure(figsize=(10,10))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(sample_imgs[i])
    plt.title("Dog" if sample_labels[i]==1 else "Cat")
    plt.axis("off")
plt.suptitle("Sample training images")
plt.show()

"""CNN"""

# Part 4: Model 1 - Simple CNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# Build model
model1 = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')  # binary classification
])

model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model1.summary()

# Train the model
history1 = model1.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10
)

# Evaluate on test set
test_loss, test_acc = model1.evaluate(test_gen)
print(f"Test Accuracy: {test_acc*100:.2f}%")

# Plot training history
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history1.history['loss'], label='train_loss')
plt.plot(history1.history['val_loss'], label='val_loss')
plt.title("Loss")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history1.history['accuracy'], label='train_acc')
plt.plot(history1.history['val_accuracy'], label='val_acc')
plt.title("Accuracy")
plt.legend()
plt.show()

# Part 4.2: Classification Report & Confusion Matrix
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import numpy as np

# Get predictions on test set
test_gen.reset()  # ensure correct order
pred_probs = model1.predict(test_gen)
pred_labels = (pred_probs > 0.5).astype(int).reshape(-1)

# True labels
true_labels = test_gen.classes

# Classification report
print("Classification Report:")
print(classification_report(true_labels, pred_labels, target_names=['Cat','Dog']))

# Confusion matrix
cm = confusion_matrix(true_labels, pred_labels)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Cat','Dog'], yticklabels=['Cat','Dog'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

"""VGG16 Transfer Learning"""

# Part 5: Model 2 - VGG16 Transfer Learning
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam

# Load VGG16 base (without top)
vgg_base = VGG16(weights='imagenet', include_top=False, input_shape=(128,128,3))
vgg_base.trainable = False  # freeze base layers

# Build top classifier
model2 = Sequential([
    vgg_base,
    GlobalAveragePooling2D(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model2.compile(optimizer=Adam(learning_rate=1e-4), loss='binary_crossentropy', metrics=['accuracy'])
model2.summary()

# Train model
history2 = model2.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10
)

# Evaluate on test set
test_loss2, test_acc2 = model2.evaluate(test_gen)
print(f"VGG16 Test Accuracy: {test_acc2*100:.2f}%")

# Plot training history
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history2.history['loss'], label='train_loss')
plt.plot(history2.history['val_loss'], label='val_loss')
plt.title("Loss - VGG16")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history2.history['accuracy'], label='train_acc')
plt.plot(history2.history['val_accuracy'], label='val_acc')
plt.title("Accuracy - VGG16")
plt.legend()
plt.show()

# Classification report & confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

test_gen.reset()
pred_probs2 = model2.predict(test_gen)
pred_labels2 = (pred_probs2 > 0.5).astype(int).reshape(-1)
true_labels = test_gen.classes

print("VGG16 Classification Report:")
print(classification_report(true_labels, pred_labels2, target_names=['Cat','Dog']))

cm2 = confusion_matrix(true_labels, pred_labels2)
plt.figure(figsize=(6,5))
sns.heatmap(cm2, annot=True, fmt='d', cmap='Greens', xticklabels=['Cat','Dog'], yticklabels=['Cat','Dog'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("VGG16 Confusion Matrix")
plt.show()

"""ResNet50 Transfer Learning"""

# Part 6: Model 3 - ResNet50 Transfer Learning
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam

# Load ResNet50 base (pretrained on ImageNet)
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(128,128,3))

# Freeze base layers
for layer in base_model.layers:
    layer.trainable = False

# Add custom top layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
preds = Dense(1, activation='sigmoid')(x)

model3 = Model(inputs=base_model.input, outputs=preds)
model3.compile(optimizer=Adam(learning_rate=0.0001), loss='binary_crossentropy', metrics=['accuracy'])
model3.summary()

# Train the model (keep epochs small to save time)
history3 = model3.fit(
    train_gen,
    validation_data=val_gen,
    epochs=5  # 5-10 epochs usually enough for transfer learning
)

# Evaluate on test set
test_loss3, test_acc3 = model3.evaluate(test_gen)
print(f"ResNet50 Test Accuracy: {test_acc3*100:.2f}%")

# Plot training history
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history3.history['loss'], label='train_loss')
plt.plot(history3.history['val_loss'], label='val_loss')
plt.title("ResNet50 Loss")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history3.history['accuracy'], label='train_acc')
plt.plot(history3.history['val_accuracy'], label='val_acc')
plt.title("ResNet50 Accuracy")
plt.legend()
plt.show()

# Part 6.1: Classification report & confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

test_gen.reset()
pred_probs3 = model3.predict(test_gen)
pred_labels3 = (pred_probs3>0.5).astype(int).reshape(-1)
true_labels = test_gen.classes

print("ResNet50 Classification Report:")
print(classification_report(true_labels, pred_labels3, target_names=['Cat','Dog']))

cm3 = confusion_matrix(true_labels, pred_labels3)
plt.figure(figsize=(6,5))
sns.heatmap(cm3, annot=True, fmt='d', cmap='Blues', xticklabels=['Cat','Dog'], yticklabels=['Cat','Dog'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("ResNet50 Confusion Matrix")
plt.show()

"""MobileNetV2 Transfer Learning"""

# Part 7: Model 4 - MobileNetV2 Transfer Learning
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam

# Load MobileNetV2 base (pretrained on ImageNet)
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(128,128,3))

# Freeze base layers
for layer in base_model.layers:
    layer.trainable = False

# Add custom top layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
preds = Dense(1, activation='sigmoid')(x)

model4 = Model(inputs=base_model.input, outputs=preds)
model4.compile(optimizer=Adam(learning_rate=0.0001), loss='binary_crossentropy', metrics=['accuracy'])
model4.summary()

# Train the model (short epochs for speed)
history4 = model4.fit(
    train_gen,
    validation_data=val_gen,
    epochs=5
)

# Evaluate on test set
test_loss4, test_acc4 = model4.evaluate(test_gen)
print(f"MobileNetV2 Test Accuracy: {test_acc4*100:.2f}%")

# Plot training history
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history4.history['loss'], label='train_loss')
plt.plot(history4.history['val_loss'], label='val_loss')
plt.title("MobileNetV2 Loss")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history4.history['accuracy'], label='train_acc')
plt.plot(history4.history['val_accuracy'], label='val_acc')
plt.title("MobileNetV2 Accuracy")
plt.legend()
plt.show()

# Classification report & confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

test_gen.reset()
pred_probs4 = model4.predict(test_gen)
pred_labels4 = (pred_probs4>0.5).astype(int).reshape(-1)
true_labels = test_gen.classes

print("MobileNetV2 Classification Report:")
print(classification_report(true_labels, pred_labels4, target_names=['Cat','Dog']))

cm4 = confusion_matrix(true_labels, pred_labels4)
plt.figure(figsize=(6,5))
sns.heatmap(cm4, annot=True, fmt='d', cmap='Blues', xticklabels=['Cat','Dog'], yticklabels=['Cat','Dog'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("MobileNetV2 Confusion Matrix")
plt.show()

"""EfficientNetB0 Transfer Learning"""

# Part 8: Model 5 - EfficientNetB0 Transfer Learning
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam

# Load EfficientNetB0 base (pretrained on ImageNet)
base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(128,128,3))

# Freeze base layers
for layer in base_model.layers:
    layer.trainable = False

# Add custom top layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
preds = Dense(1, activation='sigmoid')(x)

model5 = Model(inputs=base_model.input, outputs=preds)
model5.compile(optimizer=Adam(learning_rate=0.0001), loss='binary_crossentropy', metrics=['accuracy'])
model5.summary()

# Train the model (short epochs)
history5 = model5.fit(
    train_gen,
    validation_data=val_gen,
    epochs=5
)

# Evaluate on test set
test_loss5, test_acc5 = model5.evaluate(test_gen)
print(f"EfficientNetB0 Test Accuracy: {test_acc5*100:.2f}%")

# Plot training history
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history5.history['loss'], label='train_loss')
plt.plot(history5.history['val_loss'], label='val_loss')
plt.title("EfficientNetB0 Loss")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history5.history['accuracy'], label='train_acc')
plt.plot(history5.history['val_accuracy'], label='val_acc')
plt.title("EfficientNetB0 Accuracy")
plt.legend()
plt.show()

# Classification report & confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

test_gen.reset()
pred_probs5 = model5.predict(test_gen)
pred_labels5 = (pred_probs5>0.5).astype(int).reshape(-1)
true_labels = test_gen.classes

print("EfficientNetB0 Classification Report:")
print(classification_report(true_labels, pred_labels5, target_names=['Cat','Dog']))

cm5 = confusion_matrix(true_labels, pred_labels5)
plt.figure(figsize=(6,5))
sns.heatmap(cm5, annot=True, fmt='d', cmap='Blues', xticklabels=['Cat','Dog'], yticklabels=['Cat','Dog'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("EfficientNetB0 Confusion Matrix")
plt.show()

"""User input"""

from google.colab import files
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import numpy as np

def preprocess_input_img(img_path):
    img = image.load_img(img_path, target_size=(128,128))
    x = image.img_to_array(img)/255.0
    x = np.expand_dims(x, axis=0)
    return x

def predict_model(model, x):
    pred = model.predict(x)[0][0]
    label = "Dog" if pred>0.5 else "Cat"
    return pred, label

models_dict = {
    "Simple CNN": model1,
    "VGG16": model2,
    "ResNet50": model3,
    "MobileNetV2": model4,
    "EfficientNetB0": model5
}

while True:
    uploaded = files.upload()
    img_path = list(uploaded.keys())[0]
    x = preprocess_input_img(img_path)

    print(f"\nPredictions for {img_path}:")
    for name, model in models_dict.items():
        pred_prob, pred_label = predict_model(model, x)
        print(f"{name}: {pred_label} (probability={pred_prob:.4f})")

    # Show image
    plt.imshow(image.load_img(img_path))
    plt.axis("off")
    plt.title(f"Uploaded Image: {img_path}")
    plt.show()

    cont = input("Upload another image? (y/n): ")
    if cont.lower() != 'y':
        break